name: CI
on:
  push:
    branches: [ develop, main, 'feature/**' ]
  pull_request:
    branches: [ develop, main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build (si usas Maven)
        run: |
          if [ -f "app/backend/pom.xml" ]; then mvn -f app/backend/pom.xml -B -DskipTests package; fi
          if [ -f "playground/backend-base/pom.xml" ]; then mvn -f playground/backend-base/pom.xml -B -DskipTests package; fi
